options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/presales-464509/github.com/akshayi10084/n8n-cloud-run:$COMMIT_SHA'
      - '.'

images:
  - 'gcr.io/presales-464509/github.com/akshayi10084/n8n-cloud-run:$COMMIT_SHA'
